
file1 = open("dio.txt","w")
file1.write("KONO DIO DAAA")
file1.close()
file2 = open("wurdo.txt","w")
file2.write("You expected Output but it was me DIO")
file2.close()
file1 = open("dio.txt","r")
file2 = open("wurdo.txt","r")
file3 = open("output.txt","w")
file3.write(file1.read())
file3.write(file2.read())
file1.close()
file2.close()
file2.close()
print("Data copied successfully!!!")